apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.fullname" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "postgresql.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: tcp-postgresql
      port: {{ .Values.service.port }}
      targetPort: 5432
